from __future__ import annotations

import base64
import os
from pathlib import Path
import re
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))


def _ensure_local_env() -> None:
    root = Path("/tmp/trailforge-route-matrix")
    secret_dir = root / "secrets"
    secret_dir.mkdir(parents=True, exist_ok=True)
    key_path = secret_dir / "backup_encryption_key"
    if not key_path.exists() or not key_path.read_bytes().strip():
        key_path.write_bytes(base64.urlsafe_b64encode(os.urandom(32)))
    key_path.chmod(0o600)

    os.environ.setdefault("DATABASE_URL", f"sqlite+pysqlite:///{root / 'db.sqlite'}")
    os.environ.setdefault("TF_DATABASE_URL", f"sqlite+pysqlite:///{root / 'db.sqlite'}")
    os.environ.setdefault("TF_BACKUP_ENCRYPTION_KEY_PATH", str(key_path))
    os.environ.setdefault("TF_BACKUP_ROOT", str(root / "backups"))
    os.environ.setdefault("TF_ASSET_STORAGE_ROOT", str(root / "assets"))
    os.environ.setdefault("TF_BOOTSTRAP_CREDS_PATH", str(root / "bootstrap" / "admin_credentials.txt"))
    os.environ.setdefault("TF_TOKEN_ENCRYPTION_KEY_PATH", str(root / "bootstrap" / "token_encryption.key"))


def _route_to_regex(path: str) -> re.Pattern[str]:
    escaped = re.escape(path)
    template = re.sub(r"\\\{[^}]+\\\}", r"[^/]+", escaped)
    return re.compile(template)


def main() -> int:
    _ensure_local_env()

    from app.main import app  # imported after env setup

    test_files = sorted(Path("tests").glob("test_*.py"))
    test_content = {file_path: file_path.read_text(encoding="utf-8") for file_path in test_files}

    routes: list[tuple[str, str]] = []
    for route in app.routes:
        path = getattr(route, "path", None)
        methods = getattr(route, "methods", None)
        if not path or not methods or not path.startswith("/api/"):
            continue
        for method in sorted(method for method in methods if method not in {"HEAD", "OPTIONS"}):
            routes.append((method, path))

    routes.sort(key=lambda item: (item[1], item[0]))

    lines: list[str] = []
    lines.append("# API Route to Test Matrix")
    lines.append("")
    lines.append("Generated by `python scripts/route_test_matrix.py`.")
    lines.append("")
    lines.append("| Method | Route | Evidence files |")
    lines.append("|---|---|---|")

    covered = 0
    for method, path in routes:
        pattern = _route_to_regex(path)
        matches: list[str] = []
        for file_path, content in test_content.items():
            if pattern.search(content):
                matches.append(file_path.name)
        if matches:
            covered += 1
            evidence = ", ".join(matches)
        else:
            evidence = "_none found_"
        lines.append(f"| {method} | `{path}` | {evidence} |")

    lines.append("")
    lines.append(f"Coverage evidence rows with at least one test-reference match: **{covered}/{len(routes)}**")

    output_path = Path("tests") / "route_test_matrix.md"
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
